name: CI Python avec uv

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Linting avec Ruff
    runs-on: ubuntu-latest
    
    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4
    
    - name: Installer uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Configurer Python
      run: uv python install
    
    - name: Installer les dépendances
      run: uv sync --dev
    
    - name: Vérification avec Ruff
      run: uv run ruff check .
  
  test:
    name: Tests avec pytest
    runs-on: ubuntu-latest
    
    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4
    
    - name: Installer uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Configurer Python
      run: uv python install
    
    - name: Installer les dépendances
      run: uv sync --dev
    
    - name: Lancer les tests avec pytest
      run: uv run pytest